matrix:
  include:
  - language: python
    python: 3.8
    script:
    - black scripts --check
    - scripts/generate-decks.py $TRAVIS_TAG
    deploy:
      provider: releases
      api_key:
        secure: TIeZG35IB52bU9h8phrQZZXpcLMpPfakZMAYa796qrF4GL07q16kHV219A+8pycwYHpZ+wrJ5y1pyjJObwaq9v3e5iqD6OXrLQet/LApYMB8OyiKhCDE1EfjHBg9dH6jelXP5wLc5tYHsZrlRS9OiD/rAU4kojC9riHfPPrxZZ4wgW+PH6rLg6MAnwh7ooX0UN6CbOiUl5SpN5To4N1up7QW+95CaNjZ2/2WtWoIoHUwSbqKfibvu1tnv2NFS3fjE3ex9lerXGl6APV5yy73cUyHWMMCMNMlSYqviWmS7qc2FTFwouazLo+0XgWz6Krh5z7sDH+N7MkkbC8BhdxZkW7UWrBWysJaxNnSWb0VfD7c2+iq7apYrmpizwZC551lE+pKamKKIRahegPLqr9wjp9yr/+sqGM+DVsK098lF6l8/tvM0A4mgG9J1wg7De6Rv4JEgeMhFFP04tulPRrXJfciIny+9IExqmq1LvoaXTR6z6+LTEnQ96F17TjrtQNVL1ilMV8fh0gFw7suCxCmOBYyaBp0KPkJKHrDZAS7nTb0YOgPnFB+NsudledjBP1EawT3/03cX7eRWq605a2NSm9RT2RGZFaRqMC6DzaIMXBrRNtCzPgTd7OjgncGHA98Q6KxUJntl28CoIhOKBAcA4gp++7NZH2uYu6r8c+6wu4=
      file_glob: true
      file: decks/*
      skip_cleanup: true
      on:
        repo: jamsinclair/open-anki-jlpt-decks
        branch: master
        tags: true
  - language: node_js
    node_js: 12
    script:
    - npm run lint
