version: 2.1

orbs:
  node: circleci/node@1.1.6
  python: circleci/python@0.2.1

jobs:
  lint-js:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --ignore-scripts
      - run:
          command: npm run lint
          name: Lint

  lint-python:
    executor: python/default
    steps:
      - checkout
      # Manually handle caching until circleci python orb is fixed
      # https://github.com/CircleCI-Public/python-orb/issues/27
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "requirements.txt" }}
      - python/install-deps
      - save_cache:
          key: pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.local/bin/
            - /home/circleci/.local/lib/
      - run:
          command: black scripts --check
          name: Lint

  build:
    executor: python/default
    steps:
      - checkout
      # Manually handle caching until circleci python orb is fixed
      # https://github.com/CircleCI-Public/python-orb/issues/27
      - run: scripts/csv-to-anki.py
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - decks/*

  release:
    executor: python/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls /tmp/workspace

workflows:
  build-and-release:
    jobs:
      - lint-js
      - lint-python
      - build
      - release
          requires:
            - build
