version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
         name: Lint
         command: black scripts --check