name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
        npm install
    - name: Lint
      run: |
        black scripts --check
        npm run lint

    - name: Set Git Tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo GIT_TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV

    - name: Generate Decks
      run: scripts/generate-decks.py $GIT_TAG

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          decks/*
