name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
        npm install
    - name: Lint
      run: |
        black scripts --check
        npm run lint
    - name: Generate Decks
      run: scripts/generate-decks.py
